const widget = [
  {
    title: "Revenue",
    daily: 123,
    monthly: "monthly",
    yearly: "yearly",
    icon: " ri-money-dollar-circle-line",
    bgcolor: "bg-soft-success",
  },
  {
    title: "Brands",
    daily: 123,
    monthly: "monthly",
    yearly: "yearly",
    icon: " bx bx-certification",
    bgcolor: "bg-soft-primary",
  },
  {
    title: "Projects",
    daily: 123,
    monthly: "monthly",
    yearly: "yearly",
    icon: " bx bx-briefcase",
    bgcolor: "bg-soft-primary",
  },
  {
    title: "Active Taskers",
    daily: 123,
    monthly: "monthly",
    yearly: "ytd",
    icon: " bx bx-user-check",
    bgcolor: "bg-soft-warning",
  },
  {
    title: "Tasks",
    daily: 123,
    monthly: "monthly",
    yearly: "yearly",
    icon: " ri-todo-line",
    bgcolor: "bg-soft-success",
  },
  {
    title: "Payouts",
    daily: 123,
    monthly: "monthly",
    yearly: "yearly",
    icon: "ri-exchange-dollar-line",
    bgcolor: "bg-soft-danger",
  },
  {
    title: "Margin",
    daily: 123,
    monthly: "monthly",
    yearly: "yearly",
    icon: " ri-bar-chart-fill",
    bgcolor: "bg-soft-info",
  },
  {
    title: "App Installs",
    daily: 123,
    monthly: "monthly",
    yearly: "ytd",
    icon: " ri-install-line ",
    bgcolor: "bg-soft-warning",
  },
  {
    title: "Invoice",
    daily: 123,
    monthly: "monthly",
    yearly: "yearly",
    icon: " bx bx-rupee ",
    bgcolor: "bg-soft-danger",
  },
  {
    title: "Collection",
    daily: 123,
    monthly: "monthly",
    yearly: "yearly",
    icon: " ri-hand-coin-line",
    bgcolor: "bg-soft-danger",
  },
];

export { widget };

// ri-folder-download-fill
